version: "3"

services:

  client-app:
    build: ./frontend
    ports: 
      - 3000:3000

  backend-service:
    build: ./
    ports:
      - 8080:8080    
  
  meankube-db:
    image: mongo
    ports:
      - 27017:27017    


